language: r
sudo: true
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq

apt_packages:
  - libudunits2-dev
  - libv8-3.14-dev
  - libproj-dev
  - libgeos++-dev
  - libgdal-dev

compiler:
  - clang
